# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (8)
# #########################################################################

class ExtractedEntity(BaseModel):
    name: typing.Optional[str] = Field(default=None, description='The entity name as it appears in text')
    type: typing.Optional[types.EntityType] = None
    subtype: typing.Optional[str] = Field(default=None, description='Optional specific subtype, e.g. VEHICLE, ADDRESS, COMPANY')
    confidence: typing.Optional[float] = Field(default=None, description='Extraction confidence from 0.0 to 1.0')

class ExtractedPreference(BaseModel):
    category: typing.Optional[str] = Field(default=None, description='Preference category: food, music, tech, communication, etc.')
    preference: typing.Optional[str] = Field(default=None, description='The preference statement')
    context: typing.Optional[str] = Field(default=None, description='When/where this preference applies')
    confidence: typing.Optional[float] = Field(default=None, description='Preference confidence from 0.0 to 1.0')

class ExtractedReasoningStep(BaseModel):
    thought: typing.Optional[str] = Field(default=None, description='The reasoning or hypothesis behind the action — WHY it was done')
    action: typing.Optional[str] = Field(default=None, description='What action was taken or decision made')
    observation: typing.Optional[str] = Field(default=None, description='What was learned or observed from the action')
    alternatives_considered: typing.Optional[str] = Field(default=None, description='Other approaches that were weighed and rejected')
    confidence: typing.Optional[float] = Field(default=None, description='Confidence in the extraction, 0.0 to 1.0')

class ExtractedRelation(BaseModel):
    source: typing.Optional[str] = Field(default=None, description='Source entity name')
    target: typing.Optional[str] = Field(default=None, description='Target entity name')
    relation_type: typing.Optional[str] = Field(default=None, description='Relationship type, e.g. WORKS_AT, LIVES_IN, OWNS')
    confidence: typing.Optional[float] = Field(default=None, description='Relation confidence from 0.0 to 1.0')

class ExtractionOutput(BaseModel):
    entities: typing.List["ExtractedEntity"]
    relations: typing.List["ExtractedRelation"]
    preferences: typing.List["ExtractedPreference"]

class ReasoningChainInput(BaseModel):
    task: typing.Optional[str] = Field(default=None, description='The task that was solved')
    steps: typing.List["ReasoningStepInput"] = Field(description='The reasoning steps taken')
    outcome: typing.Optional[str] = Field(default=None, description='The final outcome')

class ReasoningExtractionOutput(BaseModel):
    task: typing.Optional[str] = Field(default=None, description='The overall task or question being addressed')
    steps: typing.List["ExtractedReasoningStep"] = Field(description='The reasoning steps in chronological order')
    final_conclusion: typing.Optional[str] = Field(default=None, description='The final conclusion or answer reached')
    success: typing.Optional[bool] = Field(default=None, description='Whether the task was successfully completed')

class ReasoningStepInput(BaseModel):
    thought: typing.Optional[str] = Field(default=None, description='Why this action was chosen')
    action: typing.Optional[str] = Field(default=None, description='What was done')
    observation: typing.Optional[str] = Field(default=None, description='What was learned')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
