# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ExtractedEntity": types.ExtractedEntity,
    "stream_types.ExtractedEntity": stream_types.ExtractedEntity,

    "types.ExtractedPreference": types.ExtractedPreference,
    "stream_types.ExtractedPreference": stream_types.ExtractedPreference,

    "types.ExtractedReasoningStep": types.ExtractedReasoningStep,
    "stream_types.ExtractedReasoningStep": stream_types.ExtractedReasoningStep,

    "types.ExtractedRelation": types.ExtractedRelation,
    "stream_types.ExtractedRelation": stream_types.ExtractedRelation,

    "types.ExtractionOutput": types.ExtractionOutput,
    "stream_types.ExtractionOutput": stream_types.ExtractionOutput,

    "types.ReasoningChainInput": types.ReasoningChainInput,
    "stream_types.ReasoningChainInput": stream_types.ReasoningChainInput,

    "types.ReasoningExtractionOutput": types.ReasoningExtractionOutput,
    "stream_types.ReasoningExtractionOutput": stream_types.ReasoningExtractionOutput,

    "types.ReasoningStepInput": types.ReasoningStepInput,
    "stream_types.ReasoningStepInput": stream_types.ReasoningStepInput,


    "types.EntityType": types.EntityType,

}